### ISSUE TITLE
pop-up browser not working

### ISSUE THREAD

**Issue by LeahLeelah** [3-manifolds/SnapPy#72] opened 2022-08-16 01:04 UTC
I have just downloaded SnapPy on my windows computer and tried using the Manifold.browse command but no pop-up comes up. I just get the following message in brackets:

function Manifold.browse

**Comment by NathanDunfield** [comment] 2022-08-16 01:15
I think the problem is that you need to call the function by adding `()` at the end:
```
In [1]: M = Manifold('m004')

In [2]: M.browse()
```
Does it work if you do that?

**Comment by LeahLeelah** [comment] 2022-08-16 01:33
Thank you so much!! It worked. I am very new at this.
Thank you thank you!
Much appreciated.

**Comment by NathanDunfield** [comment] 2022-08-16 01:36
Glad to hear it, closing this ticket.

**Closed by NathanDunfield** 2022-08-16 01:36 UTC
